version: "3"
 
services:
  miservicio_mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=TFN
      - MYSQL_ROOT_PASSWORD=secreto
      - MYSQL_USER=heyner
      - MYSQL_PASSWORD=notiene
    volumes:
      # Montamos un volumen para MySQL para no perder los datos de bd
      - ./volumenes/mysql:/var/lib/mysql
    expose:
      - 3306
    ports:
      - 3306:3306
   
  miservicio_php:
    image: webdevops/php-apache
    volumes:
      - ./miweb/:/app
    expose:
      - 80
    ports:
      - 80:80
    links: 
      - miservicio_mysql
